# Business Insights

## Project Overview

This project analyzes sales data from a fictional e-commerce company using SQL. The database contains information about customers, products, and orders. The objective is to answer business questions and generate meaningful insights through SQL queries.


# Key Business Questions

- How many customers does the company have?
- Which customer spent the most money?
- Which product generated the highest revenue?
- Which product sold the most units?
- Which category generated the highest revenue?
- What is the monthly revenue trend?
- Which cities have the highest number of customers?

# Key Insights

### Customer Analysis
- Total customers were identified using SQL.
- Average customer age was calculated.
- Female customers and customers older than 25 were analyzed.
- Customer distribution across different cities was explored.

### Product Analysis
- Most expensive and cheapest products were identified.
- Electronics products were filtered for further analysis.
- Best-selling products were determined.

### Sales Analysis
- Total company revenue was calculated.
- Revenue generated by each product was analyzed.
- Revenue generated by each product category was calculated.
- Monthly revenue trends were analyzed.
- Customers with the highest spending were identified.

# SQL Concepts Used

- CREATE DATABASE
- CREATE TABLE
- INSERT INTO
- SELECT
- WHERE
- ORDER BY
- GROUP BY
- HAVING
- INNER JOIN
- COUNT()
- SUM()
- AVG()
- MAX()
- MIN()
- DISTINCT

# Conclusion

This project demonstrates how SQL can be used to design relational databases, manipulate data, perform business analysis, and generate insights that support business decision-making.